// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_YgCCKmnG41z9iuhjCaMbXkY8SojGCNA',
    appId: '1:315155634661:web:b5a0cae0a617789a0c370c',
    messagingSenderId: '315155634661',
    projectId: 'ecommerce-app-d2182',
    authDomain: 'ecommerce-app-d2182.firebaseapp.com',
    storageBucket: 'ecommerce-app-d2182.firebasestorage.app',
    measurementId: 'G-Z3E57QB0N4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIEA0jmz2wNrcB-1uMo1RwLTSJ-5q1OPo',
    appId: '1:315155634661:android:0a439b565c52f2460c370c',
    messagingSenderId: '315155634661',
    projectId: 'ecommerce-app-d2182',
    storageBucket: 'ecommerce-app-d2182.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0tUMqPMX7ie7ivtZFzvOPaSAzRNa_VMI',
    appId: '1:315155634661:ios:80c26cf7d0bd3a4e0c370c',
    messagingSenderId: '315155634661',
    projectId: 'ecommerce-app-d2182',
    storageBucket: 'ecommerce-app-d2182.firebasestorage.app',
    iosBundleId: 'com.example.minimalShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0tUMqPMX7ie7ivtZFzvOPaSAzRNa_VMI',
    appId: '1:315155634661:ios:80c26cf7d0bd3a4e0c370c',
    messagingSenderId: '315155634661',
    projectId: 'ecommerce-app-d2182',
    storageBucket: 'ecommerce-app-d2182.firebasestorage.app',
    iosBundleId: 'com.example.minimalShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_YgCCKmnG41z9iuhjCaMbXkY8SojGCNA',
    appId: '1:315155634661:web:de2f87c88db535d80c370c',
    messagingSenderId: '315155634661',
    projectId: 'ecommerce-app-d2182',
    authDomain: 'ecommerce-app-d2182.firebaseapp.com',
    storageBucket: 'ecommerce-app-d2182.firebasestorage.app',
    measurementId: 'G-5XPE81MXFY',
  );

}